version: "3.7"

secrets:
   crawler_config:
     file: config/crawler/config.toml

services:

  rabbitmq:
    image: rabbitmq:3.7.7-management
    ports:
      - "5672:5672"
      - 18080:15672
    environment:
      - RABBITMQ_DEFAULT_USER
      - RABBITMQ_DEFAULT_PASS

  processors:
    image: floschnell/flatcrawl-processors:latest
    command: yarn start
    ports:
      - "8443:8443"
    environment:
      - FLATCRAWL_DATABASE_KEY
      - FLATCRAWL_BOT_TOKEN
      - RABBITMQ_DEFAULT_USER
      - RABBITMQ_DEFAULT_PASS

  web:
    image: floschnell/flatcrawl-web:latest
    command: http-server /opt/app/public
    ports:
      - "5555:8080"

  crawlers:
    image: floschnell/flatcrawl-crawler:1.0
    command: 'bash -c "cp /run/secrets/config.toml /opt/flatcrawl/config.toml && ./crawler"'
    secrets:
      - source: crawler_config
        target: config.toml

  isochrones:
    image: floschnell/flatcrawl-isochrones:1.0
    command: node /opt/app/src/index.js
    environment:
      - OSRM_ENDPOINT_WALKING=http://routing-foot:5000
      - OSRM_ENDPOINT_BICYCLING=http://routing-bicycle:5000
      - OSRM_ENDPOINT_DRIVING=http://routing-car:5000
      - NUMBER_OF_GRID_CELLS=20
    ports:
      - "5010:3000"
  
  routing-car:
    image: osrm/osrm-backend:v5.22.0
    command: osrm-routed --algorithm mld /data/map.osrm
    volumes:
      - /opt/osm/car:/data
    ports:
      - "5000:5000"

  routing-bicycle:
    image: osrm/osrm-backend:v5.22.0
    command: osrm-routed --algorithm mld /data/map.osrm
    volumes:
      - /opt/osm/bicycle:/data
    ports:
      - "5001:5000"

  routing-foot:
    image: osrm/osrm-backend:v5.22.0
    command: osrm-routed --algorithm mld /data/map.osrm
    volumes:
      - /opt/osm/foot:/data
    ports:
      - "5002:5000"
